--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local package = PackageIndex["testez-28fc8954-5f2752ed"].Packages["testez"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package