--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local package = PackageIndex["UtilTable-a88be83f-4a5172a7"].Packages["UtilTable"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package